"""Command-line entry point for support and general AI conversations."""

import argparse
from pathlib import Path

from app.chat import chat
from app.conversation import Conversation
from app.pipeline import run_pipeline
from app.review import review_draft


DEFAULT_KB = Path(__file__).parent / "data" / "knowledge_base.json"


def _run_review(draft_response: str) -> None:
    """Interactively collect a human decision for the generated draft."""
    print("\nHuman review")
    print("[a] Approve  [e] Edit  [r] Reject")
    choice = input("Decision: ").strip().lower()
    actions = {"a": "approve", "e": "edit", "r": "reject"}
    if choice not in actions:
        print("Invalid decision. No response was approved or sent.")
        return

    edited_response = None
    if choice == "e":
        print("Enter the edited response. Finish with an empty line:")
        lines: list[str] = []
        while True:
            line = input()
            if not line:
                break
            lines.append(line)
        edited_response = "\n".join(lines)

    decision = review_draft(actions[choice], draft_response, edited_response)
    print(f"Review status: {decision.action}")
    if decision.response:
        print("\nFinal response for the support agent:\n")
        print(decision.response)
    else:
        print("The draft was rejected and will not be sent.")


def _run_chat(knowledge_base: Path, review_support: bool = False) -> None:
    """Run a multi-turn conversational session."""
    conversation = Conversation()
    print("AI chat started. Type 'exit' to stop.")

    while True:
        message = input("\nYou: ").strip()
        if message.lower() == "exit":
            break
        if not message:
            continue

        result = chat(message, conversation, knowledge_base)
        print(f"\nMode: {result.route.mode}")
        print(f"AI used: {'yes' if result.ai_used else 'no'}")
        print(f"Assistant: {result.response}")

        if result.support_result is not None:
            draft = result.support_result.draft
            print("Sources: " + (", ".join(draft.sources) if draft.sources else "none"))
            print("Status: awaiting human review")
            if review_support:
                _run_review(draft.response)


def _run_web(knowledge_base: Path, host: str, port: int) -> None:
    """Start the browser-based support interface."""
    from app.web import create_app

    create_app(knowledge_base).run(host=host, port=port, debug=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="AI-assisted support automation tool.")
    parser.add_argument("request", nargs="?", help="Incoming request or general question")
    parser.add_argument("--knowledge-base", default=DEFAULT_KB, type=Path)
    parser.add_argument("--chat", action="store_true", help="Start a multi-turn AI conversation")
    parser.add_argument(
        "--review-chat",
        action="store_true",
        help="Open human review automatically after support drafts in chat mode",
    )
    parser.add_argument("--review", action="store_true", help="Open human review after a support draft")
    parser.add_argument("--web", action="store_true", help="Start the browser-based support interface")
    parser.add_argument("--host", default="127.0.0.1", help="Web server host")
    parser.add_argument("--port", default=5000, type=int, help="Web server port")
    args = parser.parse_args()

    if args.review_chat and not args.chat:
        parser.error("--review-chat requires --chat")
    if args.web and (args.chat or args.request):
        parser.error("--web cannot be combined with a request or --chat")

    if args.web:
        _run_web(args.knowledge_base, args.host, args.port)
        return

    if args.chat:
        _run_chat(args.knowledge_base, review_support=args.review_chat)
        return

    if not args.request:
        parser.error("provide a request, use --chat, or use --web")

    result = run_pipeline(args.request, args.knowledge_base)
    print(f"Category: {result.classification.category}")
    print(f"Classification confidence: {result.classification.confidence:.2f}")
    print(f"Needs human review: {'yes' if result.classification.needs_review else 'no'}")
    print("\nKnowledge base matches:")
    for match in result.matches:
        print(f"- {match.article.title} ({match.score:.4f})")
    if not result.matches:
        print("- No sufficiently relevant articles found")

    print(f"\nDraft grounding confidence: {result.draft.confidence:.4f}")
    print(f"Draft requires human review: {'yes' if result.draft.review_required else 'no'}")
    print(f"Draft generated by AI: {'yes' if result.draft.ai_generated else 'no'}")
    print(f"Grounding note: {result.draft.grounding_note}")
    print("Sources: " + (", ".join(result.draft.sources) if result.draft.sources else "none"))
    print("\nDraft response:\n")
    print(result.draft.response)
    print("\nStatus: Awaiting human review")

    if args.review:
        _run_review(result.draft.response)


if __name__ == "__main__":
    main()
